# -*- coding: utf-8 -*-
"""Time Series Analysis_ARIMA_Profet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_3P0tcvnr3afbeR1xWSJmnCwreld0s9
"""

import pandas as pd
import numpy as np

# Load the dataset

df = pd.read_csv("AirPassengers.csv")

df.head()

df.rename(columns={"#Passengers":"Passengers"},inplace=True)

df.head()

df['Month'] = pd.to_datetime(df['Month'])

df.set_index('Month',inplace=True)

print(df.head())

# Visualizing the Time Series Data

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.plot(df.index,df['Passengers'], marker = 'o')
plt.xlabel('Month')
plt.ylabel('Passengers')
plt.title('Monthly Air Passengers')
plt.show()

df['MA12'] = df['Passengers'].rolling(window=12).mean()

df[['Passengers','MA12']].head(15)

#differncing

df['Passengers_diff'] = df['Passengers'] - df['Passengers'].shift(1)

# Decomposing of Time Series

from statsmodels.tsa.seasonal import seasonal_decompose

result = seasonal_decompose(df['Passengers'], model = 'multiplicative', period=12)

result.plot()

plt.show()

# Time Series Forecasting


# ARIMA (p,d,q)

from statsmodels.tsa.arima.model import ARIMA

train = df['Passengers'][:'1958-12']

test = df['Passengers']['1959-01':]

model = ARIMA(train, order=(2,1,2))

res = model.fit()

forecast = res.predict(steps = len(test))

forecast1 = res.predict(steps = 5)

forecast1

forecast.tail()

import pandas as pd
from prophet import Prophet

df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
df.head()

df.tail()

m = Prophet()
m.fit(df)

future = m.make_future_dataframe(periods=365)
future.head()
future.tail()

future

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

fig1 = m.plot(forecast)

fig2 = m.plot_components(forecast)

